int a = 10;
    // int *ptr;
    // ptr = &a;
    // cout<<a<<endl;
    // cout<<ptr<<endl;
    // cout<<&a<<endl;
    // cout<<*ptr<<endl;
    // cout<<&ptr<<endl;
    // ptr++;
    // cout<<*ptr<<endl;
    // cout<<ptr<<endl;